vendor/__version__.py
vendor/processors/base.py

Notes:
Migration 0024 was having issues with migrations in parent projects because it was using auth.User default model. The migration was changed to use: settings.AUTH_USER_MODEL. MAKE SURE YOU HAVE THAT SET UP IN YOU SETTING.PY FILE.

Release v0.2.5

---

develop/core/tests/test_offers.py
vendor/models/offer.py

Notes:
Added a simple method to get display information on the status for the offer, depending on the start and end date. 

Get Status Display Offer

---

develop/core/templates/core/account.html
develop/core/tests/test_customer_profile.py
develop/core/tests/test_invoice.py
develop/core/tests/test_offers.py
develop/core/views.py
develop/fixtures/developer.json
develop/fixtures/unit_test.json
vendor/apis/v1/authorizenet/views.py
vendor/locale/ja/LC_MESSAGES/django.po
vendor/models/invoice.py
vendor/models/offer.py
vendor/models/profile.py
vendor/processors/authorizenet.py
vendor/processors/base.py
vendor/templates/vendor/includes/cost_overview.html
vendor/templates/vendor/manage/subscription_detail.html
vendor/templates/vendor/payment_summary.html
vendor/tests/test_processor.py
vendor/utils.py
vendor/views/vendor.py

- Discount functionality implemented. If an offer has a product with an msrp larger than zero it will compare the offer price to see if it is discounted.
- Trial Amount implemented for AuthorizeNet. If an offer has a month free it will catch that as a discount and show up as a discount.
- Invoice has get_next_billing_date and price for recurring offers.
- cost_overview template updated to show discounts.
- Code refactor in processors/base and authorizenet to acomodate discounts in single purchases as well as recurring subscriptions.

Discount Feature

---

vendor/apis/v1/authorizenet/views.py
vendor/models/profile.py

Notes:
- When calling get_checkout_or_cart the created invoice was defaulting to defined site id instead of the profile.site.
- remove rais PermissionDenied in Authorizenet webhook to first validate that the signiture is being correctly validated. 
Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)

Bugfix Invoice get or create on profile.

---

vendor/tests/test_processor.py

Bugfix on randomizing credit card numbers on unit testsself.form_data['credit_card_form']['card_number'] = choice(self.VALID_CARD_NUMBERS

Bugfix on randomizing credit card numbers on unit testsself.form_data['credit_card_form']['card_number'] = choice(self.VALID_CARD_NUMBERS

---

develop/core/tests/test_customer_profile.py
develop/core/tests/test_products.py
develop/fixtures/unit_test.json
vendor/models/base.py

Notes:
- Created active_profile_receipts function to retrieve a list or receipts for profiles that have an active product.
- Created owners function to retrieve a list of profiles that currently own the product.
- Created inactive_profile_receipts function to get the past receipts for profiles that use to have an active product.
- Created expired_owners function to get profiles that use to have an active receipt for the product.

Product Owners, Expired Owners and their receipts

---

develop/core/tests/test_payment.py
develop/core/tests/test_subscriptions.py
vendor/models/subscription.py

Notes:
- Added Field submitted_date on Payment Model.
- Added Model Managers for Subscription and Payment Models for Reporting.
- Fixed Payment model reference on migration 0036.
- Passing the subscription instance on the subscription_cancel signal.
- Added get_next_billing_date and get_last_payment_date to Profile Model

Release v0.2.36

---

vendor/processors/authorizenet.py
vendor/processors/stripe_processor.py
vendor/tests/test_stripe.py
vendor/views/vendor.py

-  refactored builder functions to only return the object data. Function should always do one thing 
-  removed extra empty lines 
-  finished first run of captureing a subscription payment 
-  added build_[payment_method, setup_intent] 
-  added steps to charge for subscriptions on stripe_processor 

Stripe: subscription payment

---

vendor/processors/stripe_processor.py
vendor/tests/test_stripe.py

Updates for failing stripe tests:
- Noticed that placing the stripe.delete calls after the final assert were never getting called, so rearranged
- Needed to add stripe.api_version in order to use search functionality
- 5 test remain that fail and I suspect its because you are not able to search for a stripe object immediately after creation (just a hunch since search is new functionality)

updates to failing stripe tests

---

vendor/processors/stripe_processor.py
vendor/templates/vendor/includes/cost_overview.html

Notes:
- Moved `customer_setup` and `subscription_offer_setup` to `pre_authorization` function to only init them when a payment transaction is going to take place. 
- Added validation to check if the offer has any discount to add it to the invoice line items.
- Update the `process_payment` to create an invoice, add the invoice line items, and use the `stripe.Invoice.pay` call. 
- On the cost_overview.html added formatting for the per date total $##.##.

Stripe: payment invoice

---

vendor/models/invoice.py
vendor/models/offer.py
vendor/processors/authorizenet.py
vendor/processors/base.py

Notes:
- Added support for term_start_date for offers that are going to be active on a future date.
- updated teh get_transaction_id to only have the site id with the invoice id.
- On AuthorizeNet added a max length of 20 characters for the transaction_id when set to the reference id on authorizenet.

Term_start_date

---

vendor/processors/stripe_processor.py

Notes:
- Change recurring.interval_count var to be set by offer.get_period_length() instead of offer.get_payment_occurrences(). 

Stripe: bugfix subscrition-interval-count

---

develop/core/tests/test_invoice.py
develop/fixtures/unit_test.json
vendor/models/offer.py

Notes:
- Update discount unit tests.
- added additional validation on the get_best_currencies. The lenth check should be on the first item of the list if the list is not emtpy. Because the list has a set. 

Unit_test: update discounts-test

---

develop/core/views.py
vendor/processors/base.py

Notes:
-  added SubscriptionStatus.ACTIVE after successful purchase in the base processor 

Base processor/subscription-set-active

---

vendor/__version__.py
vendor/processors/authorizenet.py
vendor/processors/stripe_processor.py
vendor/tests/test_authorizenet.py

* Use cleaned data in the processor methods used when checking a credit card's validity- needed to fix a problem i'm having in TC. previously they took directly from the form data and were prone to throwing errors if form prefixes did not match. @rhimmelbauer let me know if there's any reason these cant use the cleaned_data attribute (which relies on field name and should be more reliable) instead!

Use cleaned data in processor methods

---

pyproject.toml
src/vendor/api/v1/stripe/views.py

if there is an event mismatch , return 200 along with a message that this is not the correct event for the view, so the API endpoints are not constantly erroring out unless there is an actual error. Suggested by @rhimmelbauer to cut down our errors from the stripe interface

Remove event mismatch 400

---

pyproject.toml
src/vendor/api/v1/stripe/views.py

this endpoint is failing because it cannot find the subscription id in the meta, but it is stored in the gateway id

get subscriptions by gateway id, not meta

---

pyproject.toml
src/vendor/api/v1/stripe/views.py

* Attempted fixes for [TC-4185](https://whitemoondreams.atlassian.net/browse/TC-4185): error comparing naive and aware datetimes; error when there is a receipt or payment that needs to be updated but not both. 
* Return a 200 if there is no receipt or payment that needs to be updated when the invoice is paid, because the subscription renewal task may have already done so if this is a recurring payment

Attempted fixes for 500 errors with stripe subscription renewal

---

pyproject.toml
src/vendor/processors/__init__.py

Notes:
-  removed AuthorizeNet and Stripe imports form the processor/__init__.py file to avoid having to install them both if either are not required

Release v0.3.28

---

pyproject.toml
src/vendor/processors/authorizenet.py
src/vendor/views/vendor_admin.py

Notes:
-  added name__contains because names could be truncated due to authorizenet character limit on name 
-  added alternate datetime format 
-  verion bump 
-  added the product to the receipt for successful payments

Bugfix-add-subscription-payment

---

pyproject.toml
src/vendor/processors/stripe.py

Notes:
- On the StripeProcessor under the `transaction_info['errors']` dictionary I added a user_message key if stripe returns one

Stripe user_message error

---

src/vendor/api/v1/stripe/views.py

Notes:
- changed paid_at to effective_at given that paid_at is null because there was never payment made

Bugfix Payment Failed

---

src/vendor/api/v1/stripe/views.py

Notes:
- When an invoice has $0 as a total it does not create a charge. To fix this I set the payment status to settled and the check if the stripe_invoice has an actual charge. If it does it sets the payment status to the corresponding stripe_charge.status

Bugfix on Zero total Invoice

---

pyproject.toml
src/vendor/models/profile.py
src/vendor/models/subscription.py
src/vendor/processors/authorizenet.py
src/vendor/tests/test_authorizenet.py

Notes:
- Added validations on the Subscriptions model for fetching `get_last_payment_date` and `get_next_billing_date`
- On the Profile model added a filter to remove any dates that are value None so that the sort won't through an exeption.

Bugfix-billing-dates

---

pyproject.toml
src/vendor/processors/stripe.py

Notes:
- Added discount to the Stripe Subscription creation when trial days where enabled.

Stripe Bugfix

---

pyproject.toml
src/vendor/models/offer.py
src/vendor/processors/stripe.py

* Set None as default when passing in dates so timezone.now() is not cached
* Use round instead of Decimal for converting decimals to ints
* Fix bug with tens digit where, for example, 50.1 would be charged as 50.01 instead of 50.10

Fix/decimal to int and billing_start_date
