renderbox/django-vendor

vendor/views/vendor.py
https://whitemoondreams.atlassian.net/browse/GK-3022
=> Redirect to the empty cart if there are no offer items attached

docs/conf.py, setup.py
Updated the doc generation configuration for Django Vendor
=> Updated the doc configs

vendor/models/receipt.py
- Quick function to void a receipt.
=> added model function to void a receipt

vendor/forms.py, vendor/views/vendor_admin.py
Fix on creating offer when validating default values
=> changed key to keys and added free validation on the create offer

vendor/views/vendor_admin.py
I needed to pass the request to the OfferForm.
```
----------------------------------------------------------------------
Ran 181 tests in 49.510s
```
=> need to pass the request to the OfferForm

vendor/apis/v1/authorizenet/views.py
=> Subscription Renew Bug fix

develop/core/tests/test_invoice.py, develop/develop/settings.py, develop/fixtures/developer.json, develop/fixtures/unit_test.json, vendor/__version__.py, vendor/admin.py, vendor/models/base.py, vendor/models/invoice.py, vendor/models/offer.py, vendor/models/profile.py, vendor/models/receipt.py, vendor/processors/dummy.py, vendor/views/vendor_admin.py
Notes:
- Swap function allows for swapping an existing offer in a invoice to a new offer. Both offers must share the same product.
- Added some sys/admin modifictions to remove timeouts for projects that have multple user and offers per site.
=> Invoice Swap Function

vendor/views/vendor.py
Notes:
Instead of showing a 500 error when an invaild offer is tried to be added to the cart, it redirects you to the cart and show a msg.
=> Invalid Offer takes you back to cart

develop/fixtures/unit_test.json, vendor/__version__.py, vendor/processors/base.py
=> New Sale Flag

vendor/__version__.py, vendor/admin.py, vendor/processors/base.py, vendor/templates/vendor/checkout.html, vendor/views/vendor.py
Note:
- Bug fixes on checkout process due to billing form prefix
=> Release v0.2.4

develop/core/tests/test_payment.py, develop/fixtures/unit_test.json, vendor/__version__.py, vendor/forms.py, vendor/models/payment.py, vendor/templates/vendor/manage/products.html, vendor/tests/test_processor.py
Notes:
Added helper funtion on Purchase Model to get its related receipt according to the transaction number
=> Get Receipt form transaction

vendor/__version__.py, vendor/admin.py, vendor/apis/v1/authorizenet/views.py, vendor/processors/authorizenet.py, vendor/processors/base.py
Notes:
- The webhooks checks if the incoming notification is for the first transaction of the subscription if it is, it ignores it as it has already been registered.
- Added fliters on Admin pages.
=> Bug Fix on Webhook

vendor/apis/v1/authorizenet/views.py
=> Logging added to webhook event

vendor/__version__.py
Notes:
- added more logging messages to AuthCaptureAPIView for easier traceability and debugging.
=> Release 0.2.8

develop/develop/settings.py, vendor/__version__.py, vendor/apis/v1/authorizenet/views.py, vendor/apis/v1/urls.py
Notes:
- Temporarily removed validation on authorize net webhooks in order to debug and test how the hash should be calculated.
=> Release v0.2.9

develop/develop/settings.py, vendor/admin.py, vendor/apis/v1/authorizenet/views.py, vendor/views/vendor.py
Notes:
- Added logging settings to debug authorizenet webhooks.
- Removed from readonly list transaction and amount on PaymentAdmin
- Added aditional validations on authcapture api endpoint.
=> Vendor Logging settings

vendor/__version__.py, vendor/tests/test_processor.py, vendor/views/vendor_admin.py
Notes:
- Removed SiteMixin on SubscriptoinsListView and added the filter in the queryset for products on site.
- Update test_processors to have random quantities.
=> Subscriptions Bug fix

vendor/processors/authorizenet.py
=> Authorizenet max invoice number

develop/develop/settings.py, requirements.txt, setup.py, vendor/config.py, vendor/forms.py, vendor/integrations.py, vendor/locale/ja/LC_MESSAGES/django.po, vendor/processors/authorizenet.py, vendor/templates/vendor/authorizenet_integration.html, vendor/templates/vendor/manage/processor_site_config_list.html, vendor/tests/test_processor.py, vendor/urls/vendor_admin.py, vendor/views/vendor_admin.py
Notes:
- Added django-integrations package.
- Added setup processor for AuthorizeNet Integration.
- Django projects can now have seperate authorizeNet keys for multi site projects.
=> Django-Integrations package

develop/core/tests/test_products.py, vendor/models/base.py, vendor/models/offer.py
Notes:
- If one tries to create a product with an empty SKU it will auto generate one.
=> Autocreate empty-sku

vendor/processors/authorizenet.py, vendor/processors/base.py, vendor/templates/vendor/manage/profile_list.html, vendor/tests/test_processor.py
Notes:
- Added api call to update subscription price.
- On profile_list.html added the email column to the table
=> Authorizenet: update subscription-price

.github/workflows/vendor_develop.yml
=> Cd to-many-checks

develop/core/tests/test_offers.py, develop/fixtures/extra_products.json, develop/fixtures/unit_test.json
* Update product fixtures to use dictionaries for the description field since it is a jsonfield
=> update product fixtures to use dict since it is a jsonfield

vendor/tests/test_processor.py
=> cvv and fraud alert tests

develop/develop/settings.py, vendor/apps.py, vendor/config.py, vendor/models/profile.py, vendor/processors/base.py, vendor/processors/stripe_processor.py, vendor/signals.py
Notes:
- Attached post_save and post_delete model signals for customers to create or delete customers on stripe.
- Refactored the CRUD functions for customers, product, prices, coupons and subscriptions for builders to inject the class for each action. This way you don't need to create every CRUD action for each Stripe Object
=> Stripe: crud signals

vendor/forms.py, vendor/locale/ja/LC_MESSAGES/django.po
* Update placeholders on credit card form
* Add optional select state field on billing address form
* Update translations
=> update placeholders; add select field for billing form

setup.py, vendor/api/v1/authorizenet/views.py, vendor/api/v1/stripe/views.py, vendor/api/v1/urls.py, vendor/config.py, vendor/locale/ja/LC_MESSAGES/django.po, vendor/models/subscription.py, vendor/processors/base.py, vendor/processors/stripe_processor.py, vendor/templates/vendor/integration_form.html, vendor/templates/vendor/manage/processor_site_config_list.html, vendor/urls/vendor_admin.py, vendor/views/vendor_admin.py
Notes:
- Added `StripeSubscriptionInvoicePaid` and `StripeSubscriptionPaymentFailed` as endpoint to connect as webhooks with Stripe.
- Updated the Views to configure the PaymentProcessors for each site on Vendor.
- Added function `get_offer` for the `Subscription` model.
- Added the function `subscription_payment_failed` on the base processor. 
=> Stripe: webhooks

vendor/tests/test_stripe.py
test_get_stripe_customers
test_get_vendor_offers_in_stripe
test_get_product_id_with_name
test_sync_offers
test_get_vendor_offers_not_in_stripe
=> fixed broken procesor tests

vendor/processors/authorizenet.py, vendor/processors/stripe_processor.py, vendor/signals.py, vendor/tests/test_stripe.py
Notes:
- Updated `stripe_call` to check the response on each call and save the result in `self.transaction_[info, succeded, response]`
- Update unit test to take into account this changes.
- Removed the contents of `process_payment` as it need to be re-done.
- Update subscription_payment to take into account the new parse reponse changes
=> Stripe: process response

vendor/processors/stripe_processor.py, vendor/views/vendor.py
Small sync methods needed for setup intent and subscription
=> some setup methods to get test working

develop/fixtures/unit_test.json, vendor/models/offer.py, vendor/processors/stripe_processor.py
Notes:
-  changing process_payment to have an invoice object before being charged in order to apply the discounts 
-  corrected fixture to include the discount amount 
-  added function to check if an offer has any type of discount or trial period or trial amount 
=> Stripe: coupon fixes

vendor/processors/stripe_processor.py, vendor/tests/test_stripe.py
- Fixes to tests
- Small bug fix in processor
=> updates to tests

vendor/models/offer.py, vendor/processors/__init__.py, vendor/processors/stripe_processor.py, vendor/signals.py, vendor/tests/test_stripe.py
[TC-3652](https://whitemoondreams.atlassian.net/browse/TC-3652) - Offer Signals
=> Stripe offer signals

vendor/processors/stripe_processor.py
- Methods being called from TC needed in stripe processor
=> methods being called from trainingcamp

vendor/models/invoice.py, vendor/models/offer.py
Added a subscription charge date method
=> fixed displaying subscription date correctly

develop/fixtures/recurring_offer_examples.json, develop/fixtures/site_examples.json, vendor/api/v1/stripe/views.py, vendor/processors/authorizenet.py, vendor/processors/base.py, vendor/processors/stripe_processor.py, vendor/signals.py, vendor/tests/test_authorizenet.py, vendor/tests/test_processor.py, vendor/tests/test_stripe.py, vendor/views/vendor.py
Notes:
- Bug when saving the receipt.transaction
=> Stripe: invoice successfully-paid-endpoint

vendor/signals.py
=> fix signal query

vendor/processors/stripe_processor.py
Notes:
-  on stripe_sync changed the instance.save() to update to avoid triggering the post_save() signal when we were saving the stripe_id to the instances
=> Stripe: stripe signal-updates

vendor/__version__.py, vendor/processors/authorizenet.py, vendor/processors/stripe_processor.py
Notes:
- AuthorizeNet Sync Subscriptions check if payment info is none and get safe full_name
- Stripe sync objects. on updates check if it exists on stripe if not re create the object and update to new stripe id
=> Sync Bug fixes

develop/core/tests/test_subscriptions.py, vendor/__version__.py, vendor/api/v1/stripe/views.py, vendor/forms.py, vendor/locale/ja/LC_MESSAGES/django.po, vendor/processors/base.py, vendor/processors/stripe_processor.py, vendor/templates/vendor/manage/profile_detail.html, vendor/templates/vendor/manage/receipt_list.html, vendor/templates/vendor/manage/subscription_add_payment.html, vendor/templates/vendor/manage/subscription_create.html, vendor/templates/vendor/manage/subscription_detail.html, vendor/urls/vendor_admin.py, vendor/views/vendor_admin.py
Notes:
-  added SubscriptionCreateView 
-  added None or empty string for query on subscription.payments and subscription.receipts 
-  version bump and change transaction=None to empty string 
-  added logging messages for webhooks on the stripe api endpoints 
I will add the translations once I merge to master :)
=> Stripe: api logging and Manual Subscription Create

vendor/__version__.py, vendor/models/profile.py
Note:
-  added has_future_access function on the profile model to take into account receipts that start in a future date 
=> Profile: future access

develop/core/tests/test_subscriptions.py, vendor/forms.py
Notes:
- added has_future_access function on the profile model to take into account receipts that start in a future date
=> Release v0.3.5

vendor/__version__.py, vendor/views/mixin.py
=> Has_future_access

develop/core/tests/test_subscriptions.py, vendor/forms.py, vendor/views/mixin.py
Notes:
- Added `has_future_access` to mixin
=> Release v0.3.6

vendor/views/mixin.py
Fix bug with transaction id in is_card_valid method
=> Release v0.3.8

src/vendor/models/choice.py, src/vendor/processors/authorizenet.py, src/vendor/processors/base.py
Notes:
- Added function to charge a previously saved customer profile.
=> AuthorizeNet Charge Customer Profile

pyproject.toml, src/vendor/processors/authorizenet.py, src/vendor/processors/base.py, src/vendor/processors/stripe_processor.py, src/vendor/tests/test_authorizenet.py, src/vendor/tests/test_stripe.py, src/vendor/views/vendor.py
Notes:
- Added Unit test for Charge a Customer Profile for both AuthorizeNet and Stripe Processors
=> Charge Customer Profile

pyproject.toml, src/vendor/api/v1/authorizenet/views.py, src/vendor/models/subscription.py, src/vendor/processors/authorizenet.py
Notes:
- Added Except MultipleObjectsReturned on the `update_payments_to_settled` method.
- Added validation to check that a subscription has an offer on AuthCapture API endpoint
=> Added-except-multiple-objects-returned

pyproject.toml, src/vendor/api/v1/stripe/views.py
* Find stripe subscriptions by gateway id, like StripeInvoicePaid view is doing
=> Release v0.3.20

pyproject.toml, src/vendor/api/v1/stripe/views.py, src/vendor/processors/stripe_processor.py, src/vendor/views/vendor.py
* Send cancellation to stripe when triggered on platform
* Fix bug in update payment method view
=> Relase v0.3.21

pyproject.toml, src/vendor/processors/stripe_processor.py, src/vendor/views/vendor.py
* Implement stripe processor method to update payment method for a subscription
=> Release v0.3.22

pyproject.toml, src/vendor/models/base.py
Simpler and less query intensive method of getting active and inactive owners from the product model
=> Optimize product owners methods

src/vendor/processors/base.py
* More efficient method of getting active and inactive receipts/users from the product model
=> Release v0.3.25

pyproject.toml, src/vendor/processors/stripe_processor.py
Notes:
- added on_behalf_of so that charges appear on the connected account
=> Stripe Connect on_behalf_of

src/vendor/processors/base.py
Notes:
-  added on_behalf_of so that charges appear on the connected account
=> Release 0.3.26

pyproject.toml, src/vendor/admin.py
Notes:
- fixed CustomerProfileAdmin Search, to search for username and email from the user model
=> Admin - CustomerProfile Admin Search Username and email

develop/core/tests/test_offers.py, pyproject.toml, src/vendor/api/v1/views.py
Notes:
- Added a get endpoint to the AddToCartView
=> Add-to-cart-get-link

develop/core/tests/test_invoice.py, pyproject.toml, requirements.dev.txt, src/vendor/models/invoice.py
Notes:
- Added method to clear promo offers on the invoice. Invoice.clear_promos()
=> Invoice-remove-promos

src/vendor/api/v1/stripe/views.py
Note:
- changed all return status 400 to 200 given that Stripe needs to get a 200 response otherwise it will kill the webhook
=> Stripe Payment Failed Return 200

pyproject.toml, src/vendor/processors/authorizenet.py, src/vendor/processors/base.py
Note:
-  passing each subscription amount on payment creation 
-  added character limit on the subscription name for authorizenet
=> Bugfix-subscription-payments

src/vendor/processors/base.py
Notes:
- Added the Decimal import
=> added missing Decimal import

.gitignore, src/vendor/api/v1/stripe/views.py, src/vendor/config.py, src/vendor/processors/stripe.py
Notes:
- When using applications fees you need to caclulate the stripe base fee and recurring to your applications fees.
=> Stripe Fees

develop/core/tests/test_api.py, pyproject.toml, src/vendor/api/v1/urls.py, src/vendor/api/v1/views.py, src/vendor/forms.py, src/vendor/models/choice.py, src/vendor/models/payment.py, src/vendor/processors/base.py, src/vendor/processors/stripe.py
Notes:
- Added Refund endpoint.
- Refunds are recoreded on the Payment model in the result field.
- RefundForm check is the refund amount is correct, it also accepts partial refunds
=> Stripe-refund
